//**********************************************************************************
// This file is generated by a T4 template.  Any modifications to this file will
// be overridden the next time this file is generated.  DO NOT MODIFY THIS FILE!!!
//**********************************************************************************
using System;
using System.Collections.Generic;

namespace Liekhus.EDMX.Transitive.Entities.Interfaces
{
    public interface ITransitiveRepository
    {

	    }
}
